// GENERATED by scripts/sign-legitimacy-artifacts.mjs — do not edit by hand.
// Signed registry-legitimacy artifacts (v0.3 candidate C §1). Public.
export const REGISTRY_MANIFEST = {
  "axis_version": "0.3",
  "registry_id": "prime",
  "registry_url": "https://registry.axisprime.ai",
  "keys": [
    {
      "kid": "prime-registry-2026",
      "alg": "Ed25519",
      "public_key": "cwCJBlPDW_MrIqvROUtTV7nBF2jWokdShunxzfxDjPs",
      "status": "active",
      "not_before": "2026-06-14T21:38:39Z",
      "not_after": "2027-06-14T21:38:39Z"
    }
  ],
  "endpoints": {
    "agents": "/agents",
    "operators": "/operators",
    "verify": "/verify",
    "revocation": "/revocation",
    "delegations": "/delegations"
  },
  "directory_url": "https://registry.axisprime.ai/.well-known/axis-directory",
  "signature": "dgxMbwSNI13s4oytYXjWzlf6LRRJspo3UkDS68Dd9D-ikQyN74uGMBNWPEj8YdZ5dFDp_lKypa7ppYC7c2GmAQ"
};

export const ROOT_DIRECTORY = {
  "axis_version": "0.3",
  "directory_version": 1,
  "issued_at": "2026-06-14T21:38:39Z",
  "expires_at": "2027-06-14T21:38:39Z",
  "registrars": [
    {
      "registry_id": "prime",
      "registry_url": "https://registry.axisprime.ai",
      "key_fingerprints": [
        "82a529b5e13cccac8e0ca25fad05b138b19a32ef9ea2736ed17f5c1f1c6843a9"
      ],
      "status": "certified",
      "certified_at": "2026-06-14T21:38:39Z"
    }
  ],
  "root_signature": "-hW77zrpZe_QkWfTZjSf9uvm5jviefGMVQ-1o-WavH6qENer9DE0kjHNNc37Kg63QvfRO2rFfe55iR7NyeoSBA"
};

// AXIS Prime root PUBLIC key (pin); verifiers check ROOT_DIRECTORY against it.
export const PRIME_ROOT_PUBLIC_KEY = "jHCape-3YpUAr24_y9JekNAdkLH0umI5t3koii_A338";
